# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fca0a6fc2a4c90d2fb33bb0c53e0edad17016172fe85766f584b7e6fbfb7481fdc86ab942558297f29a855580af2f3c4b914a4504b3cfd5679e483c3cc04841e

test:
  secret_key_base: 06b465850d929dfb7541f6a754fbf06dd9dee81e323083cf0f60bcecde3227ee1fa67c74a4b9b97a9ae72fd2ec3dafc8364c6dd79757976773700a5cc965af58

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
